# Numpy -  multidimensional data arrays
## Introduction

NumPy is the fundamental package for scientific computing with Python. It contains among other things:

* a powerful N-dimensional array object
* sophisticated (broadcasting) functions
* tools for integrating C/C++ and Fortran code
* useful linear algebra, Fourier transform, and random number capabilities

First, we need to import the Numpy module. Python has few different ways to import a module. 


In [1]:
import numpy
print numpy.cos(numpy.pi)

-1.0


In [1]:
import numpy as np
print np.cos(np.pi)

-1.0


In [3]:
from numpy import *
print cos(pi)

-1.0


Even though the last one makes it simpler to use the module functions, importing all the objects of a module is not a good idea, especially for a large one like the numpy.
 * The numpy namespace can conflict with the namespace of other modules (e.g., the math module) or user-defined functions 
 * It polutes your variables namespace with hundreds of objects you probably are not going to use.

In [1]:
import numpy as np
print np.cos(np.pi)

-1.0


In [2]:
%who

np	 


In [3]:
from numpy import *
print cos(pi)

-1.0


In [4]:
%who

ALLOW_THREADS	 BUFSIZE	 CLIP	 ComplexWarning	 DataSource	 ERR_CALL	 ERR_DEFAULT	 ERR_DEFAULT2	 ERR_IGNORE	 
ERR_LOG	 ERR_PRINT	 ERR_RAISE	 ERR_WARN	 FLOATING_POINT_SUPPORT	 FPE_DIVIDEBYZERO	 FPE_INVALID	 FPE_OVERFLOW	 FPE_UNDERFLOW	 
False_	 Inf	 Infinity	 MAXDIMS	 MachAr	 ModuleDeprecationWarning	 NAN	 NINF	 NZERO	 
NaN	 PINF	 PZERO	 PackageLoader	 RAISE	 RankWarning	 SHIFT_DIVIDEBYZERO	 SHIFT_INVALID	 SHIFT_OVERFLOW	 
SHIFT_UNDERFLOW	 ScalarType	 True_	 UFUNC_BUFSIZE_DEFAULT	 UFUNC_PYVALS_NAME	 WRAP	 absolute	 add	 add_docstring	 
add_newdoc	 add_newdoc_ufunc	 add_newdocs	 alen	 all	 allclose	 alltrue	 alterdot	 amax	 
amin	 angle	 any	 append	 apply_along_axis	 apply_over_axes	 arange	 arccos	 arccosh	 
arcsin	 arcsinh	 arctan	 arctan2	 arctanh	 argmax	 argmin	 argpartition	 argsort	 
argwhere	 around	 array	 array2string	 array_equal	 array_equiv	 array_repr	 array_split	 array_str	 
asanyarray	 asarray	 asarray_chkfinite	 ascontiguousarray	 asfarray	 asfortranarray	 asmatrix	 assc

## Creating `numpy` arrays

In the `numpy` package the terminology used for vectors, matrices and higher-dimensional data sets is *array*. 

There are a number of ways to initialize new numpy arrays, for example from

* a Python list or tuples
* using functions that are dedicated to generating numpy arrays, such as `arange`, `linspace`, etc.
* reading data from files

### From lists

For example, to create new vector and matrix arrays from Python lists we can use the `numpy.array` function.


In [3]:
# a vector: the argument to the array function is a Python list
v = np.array([1,2,3,4])

v

array([1, 2, 3, 4])

In [4]:
# a matrix: the argument to the array function is a nested Python list
M = np.array([[1, 2], [3, 4]])

M

array([[1, 2],
       [3, 4]])

The `v` and `M` objects are both of the type `ndarray` that the `numpy` module provides.

In [5]:
type(v), type(M)

(numpy.ndarray, numpy.ndarray)

The difference between the `v` and `M` arrays is only their shapes. We can get information about the shape of an array by using the `ndarray.shape` property.

In [6]:
M.size

4

In [7]:
v.size

4

In [6]:
v.shape

(4,)

In [7]:
M.shape

(2, 2)

The number of elements in the array is available through the `ndarray.size` property:

In [8]:
M.size

4

So far the `numpy.ndarray` looks awefully much like a Python list (or nested list). Why not simply use Python lists for computations instead of creating a new array type? 

There are several reasons:

* Python lists are very general. They can contain any kind of object. They are dynamically typed. They do not support mathematical functions such as matrix and dot multiplications, etc. Implementating such functions for Python lists would not be very efficient because of the dynamic typing.
* Numpy arrays are **statically typed** and **homogeneous**. The type of the elements is determined when array is created.
* Numpy arrays are memory efficient.
* Because of the static typing, fast implementation of mathematical functions such as multiplication and addition of `numpy` arrays can be implemented in a compiled language (C and Fortran is used).

Using the `dtype` (data type) property of an `ndarray`, we can see what type the data of an array has:

In [11]:
M.dtype

dtype('int64')

We get an error if we try to assign a value of the wrong type to an element in a numpy array:

In [12]:
M[0,0] = "hello"

ValueError: invalid literal for long() with base 10: 'hello'

If we want, we can explicitly define the type of the array data when we create it, using the `dtype` keyword argument: 

In [13]:
M = array([[1, 2], [3, 4]], dtype=complex)

M

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

Common type that can be used with `dtype` are: `int`, `float`, `complex`, `bool`, `object`, etc.

We can also explicitly define the bit size of the data types, for example: `int64`, `int16`, `float128`, `complex128`.

## Using array-generating functions

For larger arrays it is inpractical to initialize the data manually, using explicit pythons lists. Instead we can use one of the many functions in `numpy` that generates arrays of different forms. Some of the more common are:

## arange
Similar to the `range` function

In [9]:
# create a range

x = np.arange(10,30,3) # arguments: start, stop, step

x

array([10, 13, 16, 19, 22, 25, 28])

In [10]:
x = np.arange(-2, 2, 0.1)

x

array([ -2.00000000e+00,  -1.90000000e+00,  -1.80000000e+00,
        -1.70000000e+00,  -1.60000000e+00,  -1.50000000e+00,
        -1.40000000e+00,  -1.30000000e+00,  -1.20000000e+00,
        -1.10000000e+00,  -1.00000000e+00,  -9.00000000e-01,
        -8.00000000e-01,  -7.00000000e-01,  -6.00000000e-01,
        -5.00000000e-01,  -4.00000000e-01,  -3.00000000e-01,
        -2.00000000e-01,  -1.00000000e-01,   1.77635684e-15,
         1.00000000e-01,   2.00000000e-01,   3.00000000e-01,
         4.00000000e-01,   5.00000000e-01,   6.00000000e-01,
         7.00000000e-01,   8.00000000e-01,   9.00000000e-01,
         1.00000000e+00,   1.10000000e+00,   1.20000000e+00,
         1.30000000e+00,   1.40000000e+00,   1.50000000e+00,
         1.60000000e+00,   1.70000000e+00,   1.80000000e+00,
         1.90000000e+00])

## linspace and logspace

In [12]:
# using linspace, both end points ARE included
tmp = np.linspace(0, 10, 25)
tmp.size

25

In [14]:
np.logspace(0, 10, 11, base=10)

array([  1.00000000e+00,   1.00000000e+01,   1.00000000e+02,
         1.00000000e+03,   1.00000000e+04,   1.00000000e+05,
         1.00000000e+06,   1.00000000e+07,   1.00000000e+08,
         1.00000000e+09,   1.00000000e+10])

## random data

In [15]:
# uniform random numbers ini [0,1]
np.random.rand(5,5)

array([[ 0.13792729,  0.22898003,  0.99859882,  0.84516969,  0.76938909],
       [ 0.53433405,  0.75079597,  0.53802297,  0.69789904,  0.23934449],
       [ 0.17139537,  0.56573487,  0.95357571,  0.70154339,  0.97042385],
       [ 0.05873952,  0.04546985,  0.94331673,  0.77352497,  0.36153732],
       [ 0.28396603,  0.94701416,  0.83306795,  0.83340256,  0.87357003]])

In [16]:
# standard normal distributed random numbers
np.random.randn(5,5)

array([[ 1.18360087,  0.78772109, -0.95618353,  1.32236259,  0.25593709],
       [ 0.41745033,  0.3771266 , -1.45289608, -1.07195868, -0.97186588],
       [ 0.98977589, -0.32026529, -1.55106367, -0.02064177,  2.85587273],
       [ 1.48544087, -1.00809452, -1.2495845 ,  0.53367803, -2.49439093],
       [ 0.40078004,  0.62830008,  1.10273311, -0.11005517, -0.28283753]])

## zeros and ones

In [23]:
np.zeros((4,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [26]:
tmp = np.ones((223,1000),dtype='int8')

In [25]:
np.identity(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

## File I/O


### Comma-separated values (CSV)

In [33]:
data = np.genfromtxt('./data/iris.txt',delimiter=',',dtype='float64')

In [34]:
data.shape

(150, 5)

In [35]:
data[:5]

array([[ 5.1,  3.5,  1.4,  0.2,  nan],
       [ 4.9,  3. ,  1.4,  0.2,  nan],
       [ 4.7,  3.2,  1.3,  0.2,  nan],
       [ 4.6,  3.1,  1.5,  0.2,  nan],
       [ 5. ,  3.6,  1.4,  0.2,  nan]])

We can also save numpy arrays to 

In [36]:
M = np.random.rand(3,3)

M

array([[ 0.71390978,  0.78029278,  0.32642277],
       [ 0.91171928,  0.59866641,  0.42333042],
       [ 0.38747284,  0.88700201,  0.84638609]])

In [37]:
np.savetxt("random-matrix.csv", M)

In [38]:
!cat random-matrix.csv

7.139097795731671470e-01 7.802927789380783574e-01 3.264227659327110231e-01
9.117192760370754767e-01 5.986664128850650579e-01 4.233304167592164546e-01
3.874728382674030858e-01 8.870020086314923669e-01 8.463860888534715521e-01


In [39]:
np.savetxt("random-matrix.csv", M, fmt='%.5f') # fmt specifies the format

!cat random-matrix.csv

0.71391 0.78029 0.32642
0.91172 0.59867 0.42333
0.38747 0.88700 0.84639


## Manipulating arrays

### Indexing

We can index elements in an array using the square bracket and indices:

In [40]:
# v is a vector, and has only one dimension, taking one index
v[0]

1

In [42]:
M

array([[ 0.71390978,  0.78029278,  0.32642277],
       [ 0.91171928,  0.59866641,  0.42333042],
       [ 0.38747284,  0.88700201,  0.84638609]])

In [41]:
# M is a matrix, or a 2 dimensional array, taking two indices 
M[1,1]

0.59866641288506506

If we omit an index of a multidimensional array it returns the whole row (or, in general, a N-1 dimensional array) 

In [44]:
M

array([[ 0.71390978,  0.78029278,  0.32642277],
       [ 0.91171928,  0.59866641,  0.42333042],
       [ 0.38747284,  0.88700201,  0.84638609]])

In [45]:
M[0]

array([ 0.71390978,  0.78029278,  0.32642277])

The same thing can be achieved with using `:` instead of an index: 

In [47]:
M[1,:2] 

array([ 0.91171928,  0.59866641])

In [49]:
M[:,1] # column 1

array([ 0.78029278,  0.59866641,  0.88700201])

We can assign new values to elements in an array using indexing:

In [47]:
M[0,0] = 1

In [48]:
M

array([[ 1.        ,  0.46635226,  0.4070475 ],
       [ 0.53910705,  0.64968622,  0.85079048],
       [ 0.45170465,  0.97032227,  0.31628198]])

In [52]:
# also works for rows and columns
M[1,:] = 0
M[:,2] = -1

In [53]:
M

array([[ 0.71390978,  0.78029278, -1.        ],
       [ 0.        ,  0.        , -1.        ],
       [ 0.38747284,  0.88700201, -1.        ]])

## Index slicing

Index slicing is the technical name for the syntax `M[lower:upper:step]` to extract part of an array:

In [56]:
A = np.array([1,2,3,4,5])
A

array([1, 2, 3, 4, 5])

In [57]:
A[1:3]

array([2, 3])

Array slices are *mutable*: if they are assigned a new value the original array from which the slice was extracted is modified:

In [58]:
A[1:3] = [-2,-3]

A

array([ 1, -2, -3,  4,  5])

We can omit any of the three parameters in `M[lower:upper:step]`:

In [59]:
A[::] # lower, upper, step all take the default values

array([ 1, -2, -3,  4,  5])

In [55]:
A[::2] # step is 2, lower and upper defaults to the beginning and end of the array

array([ 1, -3,  5])

In [56]:
A[:3] # first three elements

array([ 1, -2, -3])

In [57]:
A[3:] # elements from index 3

array([4, 5])

Negative indices counts from the end of the array (positive index from the begining):

In [58]:
A = array([1,2,3,4,5])

In [59]:
A[-1] # the last element in the array

5

In [60]:
A[-3:] # the last three elements

array([3, 4, 5])

Index slicing works exactly the same way for multidimensional arrays:

In [60]:
A = np.array([[n+m*10 for n in range(5)] for m in range(5)])

A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [71]:
# a block from the original array
A[1:4, 1:4]

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [72]:
# strides
A[::2, ::2]

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

### Scalar-array operations

We can use the usual arithmetic operators to multiply, add, subtract, and divide arrays with scalar numbers.

In [61]:
v1 = np.arange(0, 5)

In [62]:
v1 * 2

array([0, 2, 4, 6, 8])

In [77]:
v1 + 2

array([2, 3, 4, 5, 6])

In [78]:
A * 2, A + 2

(array([[ 0,  2,  4,  6,  8],
        [20, 22, 24, 26, 28],
        [40, 42, 44, 46, 48],
        [60, 62, 64, 66, 68],
        [80, 82, 84, 86, 88]]), array([[ 2,  3,  4,  5,  6],
        [12, 13, 14, 15, 16],
        [22, 23, 24, 25, 26],
        [32, 33, 34, 35, 36],
        [42, 43, 44, 45, 46]]))

### Element-wise array-array operations

When we add, subtract, multiply and divide arrays with each other, the default behaviour is **element-wise** operations:

In [79]:
A * A # element-wise multiplication

array([[   0,    1,    4,    9,   16],
       [ 100,  121,  144,  169,  196],
       [ 400,  441,  484,  529,  576],
       [ 900,  961, 1024, 1089, 1156],
       [1600, 1681, 1764, 1849, 1936]])

In [80]:
v1 * v1

array([ 0,  1,  4,  9, 16])

If we multiply arrays with compatible shapes, we get an element-wise multiplication of each row:

In [81]:
A.shape, v1.shape

((5, 5), (5,))

In [82]:
A * v1

array([[  0,   1,   4,   9,  16],
       [  0,  11,  24,  39,  56],
       [  0,  21,  44,  69,  96],
       [  0,  31,  64,  99, 136],
       [  0,  41,  84, 129, 176]])

# Data computations

Often it is useful to store datasets in Numpy arrays. Numpy provides a number of functions to calculate statistics of datasets in arrays. 

For example, let's calculate some properties data from the Stockholm temperature dataset used above.

In [112]:
# reminder, the tempeature dataset is stored in the data variable:
shape(data)

(77431, 7)

## mean

In [54]:
#mean sepal length
np.mean(data[:,0])

5.8433333333333346

In [53]:
#mean sepal width
np.mean(data[:,1])

3.0540000000000007

## standard deviations and variance

In [55]:
np.std(data[:,0])

(0.82530129178514089, 0.1867506666666667)

In [56]:
np.var(data[:,1])

0.1867506666666667

## min and max

In [57]:
# lowest daily average temperature
data[:,0].min()

4.2999999999999998

In [58]:
# highest daily average temperature
data[:,1].max()

4.4000000000000004

## sum, prod 

In [62]:
d = np.arange(1, 10)
d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
# sum up all elements
np.sum(d)

45

In [64]:
# product of all elements
np.prod(d)

362880

In [66]:
# cummulative sum
np.cumsum(d)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])

In [67]:
# commulative product
np.cumprod(d)

array([     1,      2,      6,     24,    120,    720,   5040,  40320,
       362880])

## Reshaping, resizing and stacking arrays

The shape of an Numpy array can be modified without copying the underlaying data, which makes it a fast operation even for large arrays.

In [93]:
a = np.arange(100)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [94]:
b = np.reshape(a,(10,10))
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

We can also use the function `flatten` to make a higher-dimensional array into a vector. But this function create a copy of the data.

In [95]:
c  = b.flatten()

c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

##repeating arrays

Using function `repeat`, `tile`  we can create larger vectors and matrices from smaller ones:

In [100]:
a = np.array([[1, 2], [3, 4]])

In [102]:
# repeat each element 3 times
np.repeat(a, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [103]:
# tile the matrix 3 times 
np.tile(a, 3)

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

#### concatenate

In [148]:
b = np.array([[5, 6]])

In [149]:
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [150]:
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

#### hstack and vstack

In [151]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [152]:
np.hstack((a,b.T))

array([[1, 2, 5],
       [3, 4, 6]])

## Vectorizing functions

As mentioned several times by now, to get good performance we should try to avoid looping over elements in our vectors and matrices, and instead use vectorized algorithms. The first step in converting a scalar algorithm to a vectorized algorithm is to make sure that the functions we write work with vector inputs.

In [104]:
def increment(x):
    return x+1

In [106]:
a = np.array([-3,-2,-1,0,1,2,3])
increment(a)

array([-2, -1,  0,  1,  2,  3,  4])

Sometimes, our functions cannot be automatically vectorized.

In [107]:
def myfunc(a, b):
    "Return a-b if a>b, otherwise return a+b"
    if a > b:
        return a - b
    else:
        return a + b
myfunc(a)

TypeError: myfunc() takes exactly 2 arguments (1 given)

In [113]:
myfunc_vectorized = np.vectorize(myfunc)
myfunc_vectorized(a,b=2)

array([-1,  0,  1,  2,  3,  4,  1])

## Type casting

Since Numpy arrays are *statically typed*, the type of an array does not change once created. But we can explicitly cast an array of some type to another using the `astype` functions (see also the similar `asarray` function). This always create a new array of new type:

In [114]:
M.dtype

dtype('float64')

In [115]:
M2 = M.astype(float)

M2

array([[ 0.71055199,  0.10732567,  0.16233974],
       [ 0.70837103,  0.6156498 ,  0.54615663],
       [ 0.77960958,  0.419811  ,  0.85135521]])

In [116]:
M2.dtype

dtype('float64')

In [117]:
M3 = M.astype(bool)

M3

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)